name: Deploy Test
on:
  push:
    branches: [test]

jobs:
  deploy-test-and-destroy:
    runs-on: ubuntu-latest
    environment: test
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION:            us-east-1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init and apply
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: infrastructure/terraform/environments/test
      - name: Upload data and run Glue
        run: |
          aws s3 cp src/glue_jobs/transform.py s3://artefact-test-staging/scripts/transform.py
          aws s3 cp tests/fixtures/events.csv s3://artefact-test-raw/events/events.csv
          aws s3 cp tests/fixtures/campaign_spend.csv s3://artefact-test-raw/spend/campaign_spend.csv
          aws glue start-job-run --job-name artefact-transform-test
      - name: Run integration tests
        run: pytest tests/integration/ -v
        env:
          ENV: test
      - name: Terraform destroy (always runs)
        if: always()
        run: terraform destroy -auto-approve
        working-directory: infrastructure/terraform/environments/test